
api.gemini.prompt = bangla lyrics for karar oi louho kopat by kazi nazrul islam


mount.path = /myworkspace/mountspace/

filelocation.original = 1_input_files/
filename.original = jatio_songit
extention.original = mp4

filelocation.processing = 2_generated_files/
filename.processing = processing
extention.processing = wav

filelocation.vocals = 2_generated_files/
prefix.vocals = vocals
extention.vocals = wav

filelocation.vocals.vad = 2_generated_files/
prefix.vocals.vad = vocals_vad
extention.vocals.vad = wav

filelocation.before_sub = 2_generated_files/
prefix.before_sub = before_sub
extention.before_sub = wav

filelocation.ready4sub = 2_generated_files/
prefix.ready4sub = ready4sub
extention.ready4sub = mp4

filelocation.elevenlab = 1_input_files/
prefix.elevenlab = elevenlab
extention.elevenlab = json

filelocation.elevenlab2sub = 2_generated_files/
prefix.elevenlab2sub = elevenlab2sub
extention.elevenlab2sub = srt

filelocation.lyrics = 2_generated_files/
prefix.lyrics = lyrics
extention.lyrics = txt


filelocation.ready2up = 3_final_files/
prefix.ready2up = ready2up_
extention.ready2up = mp4

