filelocation.original = ../git-ignore-files/1_input_files/
filename.original = amar_sonar_bangla
extention.original = mp4


filelocation.vocals = ../git-ignore-files/2_generated_files/
prefix.vocals = vocals_
extention.vocals.file = mp4

filelocation.ready4sub = ../git-ignore-files/2_generated_files/
prefix.ready4sub = ready4sub_
extention.ready4sub.file = mp4

filelocation.elevenlab = ../git-ignore-files/2_generated_files/
prefix.elevenlab = elevenlab
extention.elevenlab.file = json

filelocation.elevenlab2sub = ../git-ignore-files/2_generated_files/
prefix.elevenlab2sub = elevenlab2sub
extention.elevenlab2sub.file = srt

filelocation.lyrics = ../git-ignore-files/2_generated_files/
prefix.lyrics = lyrics
extention.lyrics = txt


filelocation.ready2up = ../git-ignore-files/3_final_files/
prefix.ready2up = ready2up_
extention.ready2up = mp4

